"""empty message

Revision ID: 77548fe1c671
Revises: 
Create Date: 2022-05-01 23:45:47.835567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77548fe1c671'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code', sa.String(length=7), nullable=False),
    sa.Column('game_status', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picked_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', postgresql.UUID(), nullable=True),
    sa.Column('first_perk_id', sa.Integer(), nullable=True),
    sa.Column('second_perk_id', sa.Integer(), nullable=True),
    sa.Column('flag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_perk_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['second_perk_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards_in_hand',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'hand_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards_in_hand')
    op.drop_table('picked_cards')
    op.drop_table('hands')
    op.drop_table('players')
    op.drop_table('game_rooms')
    op.drop_table('cards')
    # ### end Alembic commands ###
