"""empty message

Revision ID: 7d7fca219769
Revises: 
Create Date: 2022-04-30 21:49:30.579926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d7fca219769'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('host', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code', sa.String(length=7), nullable=False),
    sa.Column('game_status', sa.String(length=120), nullable=False),
    sa.Column('host', postgresql.UUID(), nullable=False),
    sa.Column('current_turn', postgresql.UUID(), nullable=True),
    sa.Column('judge', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['current_turn'], ['players.id'], ),
    sa.ForeignKeyConstraint(['host'], ['players.id'], ),
    sa.ForeignKeyConstraint(['judge'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_rooms')
    op.drop_table('players')
    op.drop_table('roles')
    # ### end Alembic commands ###
